import { IsString, IsPhoneNumber, IsNotEmpty, IsOptional, IsEmail, Length } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class SendOtpDto {
  @ApiProperty({ example: '+256700000000', description: 'Phone number in E.164 format' })
  @IsString()
  @IsNotEmpty()
  phone: string;
}

export class VerifyOtpDto {
  @ApiProperty({ example: '+256700000000' })
  @IsString()
  @IsNotEmpty()
  phone: string;

  @ApiProperty({ example: '123456', description: '6-digit OTP code' })
  @IsString()
  @Length(6, 6)
  code: string;
}

export class SignUpDto {
  @ApiProperty({ example: '+256700000000' })
  @IsString()
  @IsNotEmpty()
  phone: string;

  @ApiProperty({ example: '123456' })
  @IsString()
  @Length(6, 6)
  code: string;

  @ApiPropertyOptional({ example: 'John Doe' })
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional({ example: 'john@example.com' })
  @IsOptional()
  @IsEmail()
  email?: string;

  @ApiPropertyOptional({ example: 'android' })
  @IsOptional()
  @IsString()
  platform?: string;
}

export class LoginDto {
  @ApiProperty({ example: '+256700000000' })
  @IsString()
  @IsNotEmpty()
  phone: string;

  @ApiProperty({ example: '123456' })
  @IsString()
  @Length(6, 6)
  code: string;
}

export class RefreshTokenDto {
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  refreshToken: string;
}

export class CoreRegisterDto {
  @ApiProperty({ example: 'jacob@example.com' })
  @IsEmail()
  email: string;

  @ApiProperty({ example: 'Strong password' })
  @IsString()
  @IsNotEmpty()
  password: string;

  @ApiProperty({ example: 'Jacob Odur' })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiPropertyOptional({ example: '+256700000000' })
  @IsOptional()
  @IsString()
  phone?: string;
}

export class CoreLoginDto {
  @ApiProperty({ example: 'jacob@example.com' })
  @IsEmail()
  email: string;

  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  password: string;
}

export class CoreSsoExchangeDto {
  @ApiProperty({ description: 'One-time authorization code returned by Tuku Core' })
  @IsString()
  @IsNotEmpty()
  code: string;

  @ApiProperty({ description: 'PKCE verifier generated by the Synced Android client' })
  @IsString()
  @IsNotEmpty()
  codeVerifier: string;

  @ApiProperty({ example: 'synced://auth/tuku/callback' })
  @IsString()
  @IsNotEmpty()
  redirectUri: string;
}
